#!/bin/bash
#PBS -l walltime=36:00:00,nodes=1:ppn=16
#PBS -l mem=16gb
#PBS -A ged
#PBS -m abe
#PBS -M harriet.xander@gmail.com
#export MKL_NUM_THREADS=8
#export OMP_NUM_THREADS=8

cd /mnt/scratch/alexa503/tara-project/inputs/PRJEB1787_prok_shotgun 
 
cat MS-download.list| parallel --jobs 16 curl -L -C - {} -O

#qstat -f ${PBS_JOBID}
#cat ${PBS_NODEFILE} # Output Contents of the PBS NODEFILE
#env | grep PBS # Print out values of the current jobs PBS environment variables
